### ISSUE TITLE
[iOS] Wrong app version is sent to Flurry Analytics

### ISSUE THREAD

**Issue by drakon-ag** [sdkbox/issues#18]
Steps to reproduce:
1) Install the Flurry Analytics plugin
2) Delete `AppVersion` key in `sdkbox_config.json`
3) Log an event
4) Checkout "Event Logs" in your Flurry Analytics account and observe that the `Build` number is sent instead of the `Version`.

Proposed solution:
Send the value for the key `CFBundleShortVersionString` from `Info.plist`

**Comment by yinjimmy** [comment]
Got you

**Comment by yinjimmy** [comment]
fixed, and will release in 2.3.16 (20170804)

**Comment by suzanshakya** [comment]
In sdkbox liveops configuration, FlurryAnalytics' AppVersion field is mandatory. How do you deal with it?

**Comment by yinjimmy** [comment]
1. try `AppVersion` in sdkbox_config.json
2. try `CFBundleShortVersionString` in Info.plist

what's your issue?

**Comment by suzanshakya** [comment]
@yinjimmy You didn't mention anything about liveops configuration. When liveops is enabled, AppVersion will always be present in sdkbox_config.json, because that's a mandatory field.

My issue is I have different versions in the market, right now all of them will download the same sdkbox_config.json from liveops cloud. If AppVersion were not a mandatory field, it would be absent from sdkbox_config.json, and then only Info.plist would be scanned.

**Comment by cheerayhuang** [comment]
@yinjimmy  I think it is a bug for different version apps. Setting it as an optional item could be a solution. @suzanshakya  We will discuss  it , and give you a reply asap.

**Comment by yinjimmy** [comment]
> My issue is I have different versions in the market, right now all of them will download the same sdkbox_config.json from liveops cloud.

@suzanshakya plz propose your real needs or problems, not "In sdkbox liveops configuration, FlurryAnalytics' AppVersion field is mandatory. How do you deal with it?".

And now I got your needs.

**Comment by suzanshakya** [comment]
Hi @cheerayhuang, any progress on setting optional AppVersion on sdkbox liveops?
